site_name: Nexus VR Core Documentation
site_url: https://thenexusavenger.github.io/Nexus-VR-Core
repo_name: TheNexusAvenger/Nexus-VR-Core
repo_url: https://github.com/TheNexusAvenger/Nexus-VR-Core

theme:
  name: 'material'
  palette:
    primary: 'Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Design: design.md
  - Usage:
    - Setup: usage/setup.md
    - ScreenGuis: usage/screenguis.md
    - SurfaceGuis: usage/surfaceguis.md
    - ClickDetectors: usage/clickdetectors.md
  - API:
    - Container:
      - ScreenGui: api/Container/ScreenGui.md
      - VRSurfaceGui: api/Container/VRSurfaceGui.md
    - Interaction:
      - VRPart: api/Interaction/VRPart.md
      - VRPointer: api/Interaction/VRPointer.md
      - VRPointing: api/Interaction/VRPointing.md
    - Utility:
      - PartUtility: api/Utility/PartUtility.md

markdown_extensions:
  - admonition
  - codehilite