site_name: Nexus VR Core Documentation
site_url: https://thenexusavenger.github.io/Nexus-VR-Core
repo_name: TheNexusAvenger/Nexus-VR-Core
repo_url: https://github.com/TheNexusAvenger/Nexus-VR-Core

theme:
  name: 'material'
  palette:
    primary: 'Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Design: design.md
  - Usage:
    - Setup: setup.md
    - ScreenGuis: screenguis.md
    - SurfaceGuis: surfaceguis.md
  - API:
    - Container:
      - ScreenGui: ScreenGui.md
      - VRSurfaceGui: SurfaceGui.md
    - Interaction:
      - VRPart: VRPart.md
      - VRPointer: VRPointer.md
      - VRPointing: VRPointing.md

markdown_extensions:
  - admonition
  - codehilite